---
abstract: "export variable to PHP's expression."
author:
  - 'Taku Amano, C<< <taku at toi-planning.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0
  Test::More: 0
  Tie::IxHash: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PHP-Var
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/usualoma/php-var.git
version: 0.021
